### ISSUE TITLE
Ничего не работает, убивает видевокарту и варует вайбер акаунт и блокирует виндос 7

### ISSUE THREAD

**Issue by BlathanAevon** [atorasi/InfarctGm#1]
Вот чта праисходит при запуске

![Ed68d704d42f6d35276b67795b59c01d_i-16172](https://github.com/atorasi/InfarctGm/assets/90953033/2d1e6821-83ae-45a5-8842-264b505d0e3c)

**Comment by atorasi** [comment]
это ваще пиздец

**Comment by atorasi** [comment]
прости пожалуйста пытался наебать толпу получилось плохо
